HavaDurumuBlog/Controllers/AdminMakaleController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using HavaDurumuBlog.Models;
using PagedList;
using PagedList.Mvc;

namespace HavaDurumuBlog.Controllers
{
    public class AdminMakaleController : Controller
    {

        havadurumblogDB db = new havadurumblogDB();

        // GET: AdminMakale
        public ActionResult Index(int Page=1)
        {
            var makales = db.Makales.OrderByDescending(m=>m.Makaleid).ToPagedList(Page,10);
            return View(makales);
        }

        // GET: AdminMakale/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AdminMakale/Create
        public ActionResult Create()
        {
            ViewBag.Kategoriid = new SelectList(db.Kategoris, "Kategoriid", "KategoriAd");
            return View();
        }

        // POST: AdminMakale/Create
        [HttpPost]
        public ActionResult Create(Makale makale, string etiketler, HttpPostedFileBase Foto)
        {
            if (ModelState.IsValid)
            {
                if (Foto != null)
                {
                    WebImage img = new WebImage(Foto.InputStream);
                    FileInfo fotoinfo = new FileInfo(Foto.FileName);

                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(800, 350);
                    img.Save("~/Uploads/MakaleFoto/" + newfoto);
                    makale.Foto = ("/Uploads/MakaleFoto/" + newfoto);
                }

                if (etiketler != null)
                {

                    string[] etiketdizi = etiketler.Split(',');
                    foreach (var i in etiketdizi)
                    {
                        var yenietiket = new Etiket { EtiketAdi = i };
                        db.Etikets.Add(yenietiket);
                        makale.Etikets.Add(yenietiket);
                    }
                }
                makale.Uyeid = Convert.ToInt32(Session["uyeid"]);
                makale.Okunma = 1;
                db.Makales.Add(makale);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(makale);
        }

        // GET: AdminMakale/Edit/5
        public ActionResult Edit(int id)
        {
            var makale = db.Makales.Where(m => m.Makaleid == id).SingleOrDefault();
            if (makale == null)
            {
                return HttpNotFound();
            }
            ViewBag.Kategoriid = new SelectList(db.Kategoris, "Kategoriid", "KategoriAd", makale.Kategoriid);
            return View(makale);
        }

        // POST: AdminMakale/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, HttpPostedFileBase Foto, Makale makale)
        {
            try
            {
                var makales = db.Makales.Where(m => m.Makaleid == id).SingleOrDefault();
                if (Foto != null)
                {
                    if (System.IO.File.Exists(Server.MapPath(makales.Foto)))
                    {
                        System.IO.File.Delete(Server.MapPath(makales.Foto));
                    }
                    WebImage img = new WebImage(Foto.InputStream);
                    FileInfo fotoinfo = new FileInfo(Foto.FileName);

                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(800, 350);
                    img.Save("~/Uploads/MakaleFoto/" + newfoto);
                    makales.Foto = ("/Uploads/MakaleFoto/" + newfoto);
                    makales.Baslik = makale.Baslik;
                    makales.Icerik = makale.Icerik;
                    makales.Kategoriid = makale.Kategoriid;

                    db.SaveChanges();
                    return RedirectToAction("Index");

                }
                else
                {
                    makales.Baslik = makale.Baslik;
                    makales.Icerik = makale.Icerik;
                    makales.Kategoriid = makale.Kategoriid;

                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View();

            }
            catch
            {
                ViewBag.Kategoriid = new SelectList(db.Kategoris, "Kategoriid", "KategoriAd", makale.Kategoriid);
                return View(makale);
            }
        }

        // GET: AdminMakale/Delete/5
        public ActionResult Delete(int id)
        {
            var makale = db.Makales.Where(m => m.Makaleid == id).SingleOrDefault();
            if (makale == null)
            {
                return HttpNotFound();
            }
            return View(makale);
        }

        // POST: AdminMakale/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var makales = db.Makales.Where(m => m.Makaleid == id).SingleOrDefault();
                if (makales == null)
                {
                    return HttpNotFound();
                }

                if (System.IO.File.Exists(Server.MapPath(makales.Foto)))
                {
                    System.IO.File.Delete(Server.MapPath(makales.Foto));
                }

                foreach (var i in makales.Yorums.ToList())
                {
                    db.Yorums.Remove(i);
                }

                foreach (var i in makales.Etikets.ToList())
                {
                    db.Etikets.Remove(i);
                }


                db.Makales.Remove(makales);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

HavaDurumuBlog/Views/AdminMakale/Create.cshtml
@model HavaDurumuBlog.Models.Makale

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="card">
    <div class="card-header">
        <h2>Makale Oluştur</h2>
    </div>
    @using (Html.BeginForm("Create", "AdminMakale", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal" style="margin-left:15px">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group" style="margin-top:15px">
                @Html.LabelFor(model => model.Kategoriid, "Kategoriid", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Kategoriid", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Kategoriid, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Icerik, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="Foto" id="Foto" accept=".jpg,.png,.gif,.JPEG,.jpeg" class="form-control" />
                    @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Tarih, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                    @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.Label("Etiketler", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.TextBox("Etiketler")*@
                    <input type="text" id="Etiketler" name="Etiketler" data-role="tagsinput" class="bootstrap-tagsinput" />
                </div>
            </div>



            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Kaydet" class="btn btn-primary" /> | @Html.ActionLink("Geri Dön", "Index")
                </div>
            </div>
        </div>
        <br />
    }



</div>

HavaDurumuBlog/Views/AdminMakale/Delete.cshtml
@model HavaDurumuBlog.Models.Makale

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



<div class="card">
    <div class="card-header">
        <h3>Makale silinsin mi?</h3>
    </div>
    <div class="card-body">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Kategori.KategoriAd)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Kategori.KategoriAd)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Baslik)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Baslik)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Icerik)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Icerik)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Foto)
            </dt>

            <dd>
                <img src="@Model.Foto" width="80" alt="Alternate Text" />
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Tarih)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Tarih)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Uyeid)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Uyeid)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Okunma)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Okunma)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Sil" class="btn btn-primary" /> |
                @Html.ActionLink("Geri Dön", "Index")
            </div>
        }
    </div>
</div>

HavaDurumuBlog/Views/AdminMakale/Edit.cshtml
@model HavaDurumuBlog.Models.Makale

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

    <div class="card">

        @using (Html.BeginForm("Edit", "AdminMakale", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <div class="card-header">
                    <h4>Makale Düzenle</h4>
                </div>


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Makaleid)
                <div style="margin-left:10px">
                    <div class="form-group" style="margin-top:20px">
                        @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Icerik, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Eski Foto", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <img width="80" src="@Model.Foto" alt=" " />
                            @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" name="Foto" id="Foto" accept=".jpg,.png,.gif,.JPEG,.jpeg" class="form-control" />
                            @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Tarih, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Kategoriid, "Kategoriid", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("Kategoriid", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Kategoriid, "", new { @class = "text-danger" })
                        </div>
                    </div>



                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Güncelle" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </div>
        }

        <div style="margin-left:30px">
            @Html.ActionLink("Geri Dön", "Index")

        </div>
        <br />
    </div>

HavaDurumuBlog/Views/AdminMakale/Index.cshtml
@model IPagedList<HavaDurumuBlog.Models.Makale>
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="card">
    <div class="card-header">
        <h2>Makaleler</h2>

        <p>
            @Html.ActionLink("Yeni Makale", "Create")
        </p>
    </div>
    <div style="margin-left:10px">
        <table class="table">
            <tr>
                <th>
                    @Html.Label("Kategori Adı")
                </th>
                <th>
                    @Html.Label("Başlık")
                </th>

                <th>
                    @Html.Label("Foto")
                </th>
                <th>
                    @Html.Label("Tarih")
                </th>
                <th>
                    @Html.Label("Üye id")
                </th>
                <th>
                    @Html.Label("Okunma")
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Kategori.KategoriAd)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Baslik)
                    </td>

                    <td>
                        <img width="75" src="@item.Foto" />
                    </td>
                    <td>
                        @String.Format("{0: MMMM yyyy}", item.Tarih)    @*@Html.DisplayFor(modelItem => item.Tarih)*@
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Uyeid)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Okunma)
                    </td>
                    <td>
                        @Html.ActionLink("Düzenle", "Edit", new { id = item.Makaleid }) |
                        @*@Html.ActionLink("Detay", "Details", new { id = item.Makaleid }) |*@
                        @Html.ActionLink("Sil", "Delete", new { id = item.Makaleid })
                    </td>
                </tr>
            }

        </table>

        <div class="card-footer">
            <div class="d-flex">
                <div class="pagination mx-auto">
                    @Html.PagedListPager((IPagedList)Model, Page => Url.Action("Index", new { Page }), PagedListRenderOptions.Classic)
                </div>
            </div>
        </div>
    </div>
</div>